// <auto-generated />
using System;
using Exam.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Exam.Infrastructure.Migrations
{
    [DbContext(typeof(CalculatorDbContext))]
    partial class CalculatorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Exam.Domain.Entities.CalculatorValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FutureValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("LowerBoundInterestRate")
                        .HasColumnType("real");

                    b.Property<decimal>("PresentValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RateValuesId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CalculatorValues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2021, 8, 31, 11, 59, 22, 553, DateTimeKind.Utc).AddTicks(5666),
                            DateUpdated = new DateTime(2021, 8, 31, 11, 59, 22, 553, DateTimeKind.Utc).AddTicks(5914),
                            FutureValue = 1100m,
                            LowerBoundInterestRate = 0.1f,
                            PresentValue = 1000m,
                            RateValuesId = 0,
                            Year = 0
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5624),
                            DateUpdated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5634),
                            FutureValue = 1430m,
                            LowerBoundInterestRate = 0.3f,
                            PresentValue = 1100m,
                            RateValuesId = 0,
                            Year = 0
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5734),
                            DateUpdated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5735),
                            FutureValue = 2145m,
                            LowerBoundInterestRate = 0.5f,
                            PresentValue = 1430m,
                            RateValuesId = 0,
                            Year = 0
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5770),
                            DateUpdated = new DateTime(2021, 8, 31, 11, 59, 22, 554, DateTimeKind.Utc).AddTicks(5771),
                            FutureValue = 3217.5m,
                            LowerBoundInterestRate = 0.5f,
                            PresentValue = 2145m,
                            RateValuesId = 0,
                            Year = 0
                        });
                });

            modelBuilder.Entity("Exam.Domain.Entities.RateValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<float>("IncrementalRate")
                        .HasColumnType("real");

                    b.Property<int>("MaturityYear")
                        .HasColumnType("int");

                    b.Property<float>("UpperBoundInterestRate")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("RateValues");
                });
#pragma warning restore 612, 618
        }
    }
}
